import { z } from 'zod'
import { CardDetailsTypeEnumSchema, FundingSourceEnumSchema } from '.'

export const CardDetailsSchema = z.object({
  brand: z.string().optional(),
  checkoutAttemptId: z.string().optional(),
  cupsecureplus_smscode: z.string().optional(),
  cvc: z.string().optional(),
  encryptedCard: z.string().optional(),
  encryptedCardNumber: z.string().optional(),
  encryptedExpiryMonth: z.string().optional(),
  encryptedExpiryYear: z.string().optional(),
  encryptedSecurityCode: z.string().optional(),
  expiryMonth: z.string().optional(),
  expiryYear: z.string().optional(),
  fastlaneData: z.string().optional(),
  fundingSource: FundingSourceEnumSchema.optional(),
  holderName: z.string().optional(),
  networkPaymentReference: z.string().optional(),
  number: z.string().optional(),
  recurringDetailReference: z.string().optional(),
  shopperNotificationReference: z.string().optional(),
  srcCorrelationId: z.string().optional(),
  srcDigitalCardId: z.string().optional(),
  srcScheme: z.string().optional(),
  srcTokenReference: z.string().optional(),
  storedPaymentMethodId: z.string().optional(),
  threeDS2SdkVersion: z.string().optional(),
  type: CardDetailsTypeEnumSchema.optional(),
})
