import { z } from 'zod'
import {
  AccountInfoSchema,
  AmountSchema,
  ApplicationInfoSchema,
  AuthenticationDataSchema,
  BillingAddressSchema,
  ChannelEnumSchema,
  CheckoutSessionThreeDS2RequestDataSchema,
  CompanySchema,
  DeliveryAddressSchema,
  FundOriginSchema,
  FundRecipientSchema,
  InstallmentOptionsSchema,
  LineItemSchema,
  MandateSchema,
  ModeEnumSchema,
  NameSchema,
  PlatformChargebackLogicSchema,
  RecurringProcessingModelEnumSchema,
  RiskDataSchema,
  ShopperInteractionEnumSchema,
  SplitSchema,
  StoreFiltrationModeEnumSchema,
  StorePaymentMethodModeEnumSchema,
  StringArraySchema,
  StringRecordSchema,
  ThreeDSecureDataSchema,
} from '.'

export const CheckoutSessionSchema = z.object({
  accountInfo: AccountInfoSchema.optional().nullable(),
  additionalAmount: AmountSchema.optional().nullable(),
  additionalData: StringRecordSchema.optional(),
  allowedPaymentMethods: StringArraySchema.optional(),
  amount: AmountSchema,
  applicationInfo: ApplicationInfoSchema.optional().nullable(),
  authenticationData: AuthenticationDataSchema.optional().nullable(),
  billingAddress: BillingAddressSchema.optional().nullable(),
  blockedPaymentMethods: StringArraySchema.optional(),
  captureDelayHours: z.number().optional(),
  channel: ChannelEnumSchema.optional(),
  company: CompanySchema.optional().nullable(),
  countryCode: z.string().optional(),
  dateOfBirth: z.date().optional(),
  deliverAt: z.date().optional(),
  deliveryAddress: DeliveryAddressSchema.optional().nullable(),
  enableOneClick: z.boolean().optional(),
  enablePayOut: z.boolean().optional(),
  enableRecurring: z.boolean().optional(),
  expiresAt: z.date(),
  fundOrigin: FundOriginSchema.optional().nullable(),
  fundRecipient: FundRecipientSchema.optional().nullable(),
  id: z.string(),
  installmentOptions: InstallmentOptionsSchema.optional(),
  lineItems: z.array(LineItemSchema).optional(),
  mandate: MandateSchema.optional().nullable(),
  mcc: z.string().optional(),
  merchantAccount: z.string(),
  merchantOrderReference: z.string().optional(),
  metadata: StringRecordSchema.optional(),
  mode: ModeEnumSchema.optional(),
  mpiData: ThreeDSecureDataSchema.optional().nullable(),
  platformChargebackLogic: PlatformChargebackLogicSchema.optional().nullable(),
  recurringExpiry: z.string().optional(),
  recurringFrequency: z.string().optional(),
  recurringProcessingModel: RecurringProcessingModelEnumSchema.optional(),
  redirectFromIssuerMethod: z.string().optional(),
  redirectToIssuerMethod: z.string().optional(),
  reference: z.string(),
  returnUrl: z.string(),
  riskData: RiskDataSchema.optional().nullable(),
  sessionData: z.string().optional(),
  shopperEmail: z.string().optional(),
  shopperIP: z.string().optional(),
  shopperInteraction: ShopperInteractionEnumSchema.optional(),
  shopperLocale: z.string().optional(),
  shopperName: NameSchema.optional().nullable(),
  shopperReference: z.string().optional(),
  shopperStatement: z.string().optional(),
  showInstallmentAmount: z.boolean().optional(),
  showRemovePaymentMethodButton: z.boolean().optional(),
  socialSecurityNumber: z.string().optional(),
  splitCardFundingSources: z.boolean().optional(),
  splits: z.array(SplitSchema).optional(),
  store: z.string().optional(),
  storeFiltrationMode: StoreFiltrationModeEnumSchema.optional(),
  storePaymentMethod: z.boolean().optional(),
  storePaymentMethodMode: StorePaymentMethodModeEnumSchema.optional(),
  telephoneNumber: z.string().optional(),
  themeId: z.string().optional(),
  threeDS2RequestData:
    CheckoutSessionThreeDS2RequestDataSchema.optional().nullable(),
  trustedShopper: z.boolean().optional(),
  url: z.string().optional(),
})
